---
- name: Setup Pi Hosts
  hosts: all
  become: true
  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        update_cache: true  # Corrected from 'upgrade_cache' to 'update_cache'
        upgrade: full

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - net-tools
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - gnupg-agent
          - autoconf
          - dpkg-dev
          - file
          - g++
          - gcc
          - libc-dev
          - make
          - pkg-config
          - re2c
          - wget
        state: present

    - name: Add Docker's GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Set up the Docker stable repo
      ansible.builtin.shell: |
        set -o pipefail
        echo "deb [arch=arm64] https://download.docker.com/linux/debian/ $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list
      changed_when: "'deb [arch=arm64]' not in ansible_facts['lsb']['codename']"

    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: true

    - name: Install Docker Engine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Enable and start Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

    - name: Download Docker Compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-aarch64"  # Corrected the URL
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Ensure Compose is executable
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        mode: '0755'
        state: file

    - name: Verify Compose installation
      ansible.builtin.command: docker-compose --version
      register: result
      changed_when: false

    - name: Display Compose version
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"
