---
- name: Create Containers
  hosts: all
  become: true
  tasks:
    - name: Create a directory for Docker Compose files
      ansible.builtin.file:
        path: /home/wbreiler/docker/nginx
        state: directory
        mode: '0755'

    - name: Create a Docker Compose file for Nginx
      ansible.builtin.copy:
        dest: /home/wbreiler/docker/nginx/docker-compose.yml
        content: |
          services:
            web:
              image: nginx:latest
              ports:
                - "80:80"
              volumes:
                - ./html:/usr/share/nginx/html
                - ./nginx.conf:/etc/nginx/nginx.conf
        mode: '0644'

    - name: Create a directory for Nginx HTML files
      ansible.builtin.file:
        path: /home/wbreiler/docker/nginx/html
        state: directory
        mode: '0755'

    - name: Create a sample index.html for Nginx
      ansible.builtin.copy:
        dest: /home/wbreiler/docker/nginx/html/index.html
        content: |
          <html>
          <head><title>Welcome to Nginx!</title></head>
          <body>
          <h1>Success! The Nginx container is working.</h1>
          </body>
          </html>
        mode: '0644'

    - name: Create a custom NGINX configuration
      ansible.builtin.copy:
        dest: /home/wbreiler/docker/nginx/nginx.conf
        content: |
          user  nginx;
          worker_processes  1;

          events {
              worker_connections  1024;
          }

          http {
              include       mime.types;
              default_type  application/octet-stream;

              sendfile        on;
              keepalive_timeout  65;

              server {
                  listen       80;
                  server_name  localhost;

                  location / {
                      root   /usr/share/nginx/html;
                      index  index.html;
                      autoindex on;  # Enable directory listing if needed
                  }
              }
          }
        mode: '0644'

    - name: Ensure proper ownership of HTML files
      ansible.builtin.file:
        path: /home/wbreiler/docker/nginx/html
        state: directory
        owner: www-data
        group: www-data
        recurse: true

    - name: Ensure permissions are correct for NGINX configuration
      ansible.builtin.file:
        path: /home/wbreiler/docker/nginx/nginx.conf
        state: file
        mode: '0644'

    - name: Restart NGINX container with updated configuration
      ansible.builtin.shell: |
        docker-compose down
        docker-compose up -d
      args:
        chdir: /home/wbreiler/docker/nginx