services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 443:443/tcp
    environment:
      - TZ=America/New_York
      - FTLCONF_webserver_api_password=correcthorsebatterystaple
      - FTLCONF_dns_listeningMode=all
    volumes:
      - ./etc-pihole:/etc/pihole
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - SYS_TIME
    restart: unless-stopped