---
- name: Setup and deploy multiple Docker containers
  hosts: all
  become: true

  vars_files:
    - vars/netdata.yml
    - vars/all.yml

  roles:
    - { role: apt_cache, tags: aptcache }
    - { role: setup, tags: setup }
    - { role: docker, tags: docker }
    - { role: netdata, tags: netdata }