---
- name: Install Docker and dependencies
  hosts: all
  become: true
  roles:
    - geerlingguy.docker
  vars:
    docker_users:
      - "{{ ansible_user }}"
    docker_install_compose: true
    docker_compose_version: "v2.24.5"
