---
- name: Update packages
  hosts: all
  become: true
  roles:
    - role: update_packages

- name: Install Docker
  hosts: all
  become: true
  roles:
    - role: install_docker

- name: Install Docker Compose
  hosts: all
  become: true
  roles:
    - role: install_compose

- name: Start Compose services
  hosts: all
  become: false
  roles:
    - role: manage_compose

- name: Install MinIO Client (mc)
  hosts: all
  become: false
  roles:
    - role: install_minio_client
