---
- name: Update packages (Debian-based)
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - update
    - update_packages

- name: Update packages (RHEL-based)
  ansible.builtin.dnf:
    name: "*"
  when: ansible_facts['os_family'] == "RedHat"
  tags:
    - update
    - update_packages

- name: Update packages (Alpine)
  community.general.apk:
    update_cache: true
    upgrade: true
  when: ansible_facts['os_family'] == "Alpine"
