---
- name: Install Netdata dependencies
  ansible.builtin.apt:
    name:
      - zlib1g-dev
      - uuid-dev
      - libmnl-dev
      - gcc
      - make
      - git
      - autoconf
      - autogen
      - automake
      - pkg-config
      - curl
      - jq
      - nodejs
      - python3
      - python3-pip
      - iproute2
    state: present

- name: Download and run Netdata installation script
  ansible.builtin.shell: |
    curl https://get.netdata.cloud/kickstart.sh > /tmp/netdata-kickstart.sh && \
    sh /tmp/netdata-kickstart.sh --nightly-channel \
    --claim-token {{ netdata_claim_token }} \
    --claim-rooms {{ netdata_claim_room }} \
    --claim-url {{ netdata_claim_url }}
  args:
    creates: /usr/sbin/netdata

- name: Ensure Netdata service is running and enabled
  ansible.builtin.systemd:
    name: netdata
    state: started
    enabled: true
