---
- name: Disable IPv6 in sysctl configuration
  ansible.builtin.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 1
    sysctl_set: true
    state: present
    reload: true

- name: Disable IPv6 for default interface
  ansible.builtin.sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: 1
    sysctl_set: true
    state: present
    reload: true

- name: Persist IPv6 settings in /etc/sysctl.conf
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '^net\.ipv6\.conf\.all\.disable_ipv6'
    line: 'net.ipv6.conf.all.disable_ipv6 = 1'
    state: present

- name: Persist default interface IPv6 settings in /etc/sysctl.conf
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '^net\.ipv6\.conf\.default\.disable_ipv6'
    line: 'net.ipv6.conf.default.disable_ipv6 = 1'
    state: present

- name: Apply sysctl settings
  ansible.builtin.command: sysctl -p
  changed_when: false
