---
- name: Install required packages for Docker
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
- name: Set up the stable Docker repo
  ansible.builtin.shell: |
    set -o pipefail
    echo "deb [arch=arm64] https://download.docker.com/linux/debian/ $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list
  args:
    creates: /etc/apt/sources.list.d/docker.list
- name: Update apt package index after adding Docker repo
  ansible.builtin.apt:
    update_cache: true
- name: Install Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Add current user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Download Docker Compose binary
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-aarch64
    dest: /usr/local/bin/docker-compose
    mode: "0755"

- name: Ensure Docker Compose is executable
  ansible.builtin.file:
    path: /usr/local/bin/docker-compose
    mode: "0755"
    state: file

- name: Verify Docker Compose installation
  ansible.builtin.command:
    cmd: docker-compose --version
  register: result
  changed_when: false

- name: Display Docker Compose version
  ansible.builtin.debug:
    msg: "{{ result.stdout }}"
