---
- name: Create APT proxy config file
  ansible.builtin.file:
    path: /etc/apt/apt.conf.d/00aptproxy
    state: touch
  
- name: Add APT proxy config
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/00aptproxy
    content: |
      Acquire::http::Proxy "http://10.0.0.13:3142";
    owner: root
    group: root
    mode: '0644'