---
- name: Copy compose file to ~/
  ansible.builtin.copy:
    src: ./docker-compose.yml
    dest: "{{ ansible_env.HOME }}/docker-compose.yml"
    mode: '0644'
  tags:
    - manage_docker_compose
    - docker_compose

- name: Start services
  ansible.builtin.command: docker compose up -d
  changed_when: false
  args:
    chdir: "{{ ansible_env.HOME }}"
  tags:
    - manage_docker_compose
    - docker_compose
