---
- name: Add Ansible user to the Docker group
  ansible.builtin.user:
    name: pi
    groups: docker
    append: yes

- name: Ensure Docker is running
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: Ensure the web directory exists
  ansible.builtin.file:
    path: /home/pi/web
    state: directory
    mode: '0755'
    owner: pi
    group: pi

- name: Copy premade index
  ansible.builtin.copy:
    src: "{{ index_html_src }}"
    dest: "{{ index_html_dest }}"
    owner: pi
    group: pi
    mode: '0644'
  tags:
    - copy
    - web

# Define container details as a list of dictionaries to loop through
- name: Pull Docker images
  ansible.builtin.docker_image:
    name: "{{ item.image }}"
    source: pull
  loop: "{{ containers }}"
  tags: 
    - docker

- name: Stop and remove existing containers
  community.docker.docker_container:
    name: "{{ item.name }}"
    state: absent
    force_kill: yes
  loop: "{{ containers }}"
  ignore_errors: true
  tags: 
    - cleanup

- name: Create directories for container volumes
  ansible.builtin.file:
    path: "{{ item.volume_hosts }}"
    state: directory
    mode: '0755'
    owner: pi
    group: pi
  loop: "{{ containers }}"
  when: item.volume_host is defined
  tags: 
    - setup

- name: Run the Docker containers
  community.docker.docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: started
    ports: "{{ item.ports }}"
    volumes: "{{ item.volumes }}"
    command: "{{ item.command | default(omit) }}"  # Use the custom command if defined
    restart_policy: always
  loop: "{{ containers }}"
  tags: 
    - docker
    - deployment