---
- name: Download MinIO client
  ansible.builtin.set_fact:
    minio_arch: >
      {% if ansible_architecture in ['x86_64'] %}
        amd64
      {% elif ansible_architecture in ['aarch64'] %}
        arm64
      {% elif ansible_architecture in ['armv7l'] %}
        arm
      {% else %}
        unsupported
      {% endif %}
  tags:
    - minio
    - minio_client

- name: Fail if architecture is unsupported
  ansible.builtin.fail:
    msg: "The architecture {{ ansible_architecture }} is unsupported for MinIO client installation"
  when: minio_arch == "unsupported"
  tags:
    - minio
    - minio_client

- name: Download MinIO client (mc)
  ansible.builtin.get_url:
    url: "https://dl.min.io/client/mc/release/linux-{{ minio_arch }}/mc"
    dest: /usr/local/bin/mc
    mode: '0755'
  tags:
    - minio
    - minio_client

- name: Verify MinIO client installation
  ansible.builtin.command: mc --version
  changed_when: false
  tags:
    - minio
    - minio_client
